### PR TITLE
Capacitor 5 Support

### PR DESCRIPTION
**Pull request by ghenry22**
Updated for Capacitor 5 support
Fixed iOS build
Fixed Android build

TODO: clean up all errors reported by swiftlint in plugin files
TODO: migrate Android from support library to androidx libraries (currently jetifier is enabled for automated migration but we should migrate properly and remove jetifier).  Disable jetifier and run android:verify and it will spit out a list of imports that need updating.

Currently verifies all platforms, builds and installs for Capacitor 5 projects without error.

### CODE REVIEW

**Comment by ghenry22** [comment]
Have been having some problems with this plugin using jetifier and the main project not, some build weirdness for the project vs the plugin by itself.  Also noticed that the exomedia library has a big 5.0 release in beta at the moment which updates a lot of dependencies, including androidx library updates.  Probably worth taking a look at these as part of updating.

I'll try to keep building on this PR.

**Comment by phiamo** [comment]
Amazing, thanks a lot

Gaven Henry ***@***.***> schrieb am Di., 18. Juli 2023, 03:15:

**Comment by ghenry22** [comment]
The plugin now passes verify and build without issue.

When installed in an app with capacitor 5 the app builds and runs properly now without issue.

@phiamo if you have time could you test out this branch on capacitor 5 with a demo app.  I just spun up a new empty capacitor 5 based ionic project and added the plugin to test but I haven't had time to test all of the functionality, it should be fine as nothing as really changed that would affect plugin functionality but best to test it out a bit before merging.

This would need a major version bump to the plugin as it now requires capacitor 5+. Perhaps we could bump to version 5.0.0 for this plugin as the major version is then aligned with the supported capacitor version.

I will look into the exomedia update to 5.0.0 verison in a separate branch and raise a new PR for that later.

**Comment by phiamo** [comment]
thanks a lot!!

Am Fr., 28. Juli 2023 um 02:53 Uhr schrieb Gaven Henry <
***@***.***>:

**Comment by martink635** [comment]
@phiamo Any plans to merge this?

If you need any assistance from the community please let us know

**Comment by phiamo** [comment]
@martink635 any help is appreciated, i am finding rarely time recently

**Comment by martink635** [comment]
No worries. I've tested this build and it seems to be working fine with a little tweak. On the upgrade to Capacitor 5.0 docs it says you have to [disable Jetifier](https://capacitorjs.com/docs/updating/5-0#disable-jetifier) on Android. Leaving this option in, the plugin works perfectly.

```
# gradle.properties

...
android.enableJetifier=true
```

**Pull request merged**
