### PR TITLE
changed package.json peer dep for Capacitor to 4.2

### PR DESCRIPTION
**Pull request by timstoute**
not sure that this entirely best practice, but these changes allowed me to get past the errors I described in Issue 72: https://github.com/phiamo/capacitor-plugin-playlist/issues/72

### CODE REVIEW

**Comment by phiamo** [comment]
since we still support cap3 i am thinking of some ^3.xx || ^4.xx dependency, what do you think ?

**Comment by emilsaj** [comment]
@phiamo maybe best to make a new major version of this npm package that is for capacitor 4 and then change the Peer dependency in the bumped version. This way people have options to install version according to their capacitor version.

**Comment by timstoute** [comment]
sounds good to me, I think that makes sense, and I don't have much experience in this regard, so defer to your expertise

**Comment by emilsaj** [comment]
I don't either tbh :-D But seems like the way to go

________________________________

**Comment by quarkstars** [comment]
Are you guys gonna merge this?

**Comment by phiamo** [comment]
finally

**Pull request merged**
